server:
  port: ${SERVER_PORT:9089}
payService:
  successProbability: ${SUCCESS_PROBABILITY:0.75}
project:
  title: payment system service
  description: proceed payment and return order with payment status
spring:
  application:
    name: payService
logging:
  org.temkarus0070.payservice: ${LOGGING_LEVEL:INFO}


opentracing.jaeger:
  udp-sender:
    host: ${JAEGER_HOST:localhost}
    port: 6831
  log-spans: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true